help(read.xls)
iris <- read.csv(file.path("C:\\Users\\jhon quiceno\\Downloads", "SECOP_I.csv"), stringsAsFactors = FALSE)
head(iris)
names(iris)
filtro <- c("Borrador", "Terminado Anormalmente después de Convocado", "Convocado")
iris <- subset(iris, !(iris$Identific.del.Represen.Legal %in% "No Definido"))
datos_numericos <- data.frame(as.numeric(gsub(",", "", iris$Cuantia.Proceso)), as.numeric(gsub(",", "", iris$ID.Familia)), as.numeric(gsub(",", "", iris$ID.Clase)), as.numeric(gsub(",", "", iris$ID.Ajudicacion)), as.numeric(gsub(",", "", iris$Identificacion.del.Contratista))
, as.numeric(gsub(iris$Identific.del.Represen.Legal)), as.numeric(gsub(",", "", iris$Plazo.de.Ejec.del.Contrato)), as.numeric(gsub(",", "", iris$Cuantia.Contrato)), as.numeric(gsub(",", "", iris$Cuantia.Proceso)), as.numeric(gsub(",", "", iris$Valor.Contrato.con.Adiciones)) )
colnames(datos_numericos) <- c( "IdFa", "IdCla", "IdAd", "IdContratista", "IdReprese", "PlazoEje", "CuantiaC", "ContratoAD")
datos_depurados <- subset(iris, !(iris$Estado.del.Proceso %in% filtro))
cor(iris$ID.Objeto.a.Contratar,iris$Cuantia.Contrato)
pairs(datos_numericos)
cor(datos_numericos)
dat <- data.frame(as.numeric(gsub(",", "", iris$ID.Familia)), as.numeric(gsub(",", "", iris$ID.Clase)), as.numeric(gsub(",", "", iris$ID.Ajudicacion)), as.numeric(gsub(",", "", iris$Identificacion.del.Contratista)))
dt <- as.numeric(gsub(",", "", iris$Identificacion.del.Contratista))