//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public System.Guid IdRegistro { get; set; }
        public System.Guid IdCiudadOrigen { get; set; }
        public System.Guid IdCiudadDestino { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan HoraSalida { get; set; }
        public System.TimeSpan HoraLlegada { get; set; }
        public string NumeroVuelo { get; set; }
        public System.Guid IdAerolinea { get; set; }
        public int IdEstadoVuelo { get; set; }
        public bool TipoVuelo { get; set; }
    
        public virtual Aerolineas Aerolineas { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
